url: "https://simbricks.github.io/"
baseurl: ""
domain: "simbricks.github.io"
title: "SimBricks"
description: "SimBricks is an open-source, modular simulation framework enabling full end-to-end evaluation of modern heterogeneous systems by combining battle-tested simulators for different system components like machines (e.g. QEMU, gem5, Simics), hardware components (e.g. Verilator, Tofino, FEMU SSD), and networks (e.g. ns-3, OMNeT++). SimBricks is fast, scalable, accurate and deterministically connects and synchronizes simulators while being able to run unmodified full system stacks, including applications, operating systems such as Linux, and hardware RTL."
logo: "https://simbricks.github.io/assets/images/simbricks_logo.svg"

include:
  - _pages
exclude:
  - README.md

collections:
  projects:
    output: true
    permalink: /projects/:path.html

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"


kramdown:
  # set header offset for markdown parser as we use h1 as page title, so headers
  # in the content need to start at h2
  header_offset: 1
