url: "https://simbricks.github.io/"
baseurl: ""
domain: "simbricks.github.io"
title: "SimBricks"
logo: "https://simbricks.github.io/assets/images/simbricks_logo.svg"
logo_png: "https://simbricks.github.io/assets/images/simbricks_logo.png"

include:
  - _pages
  - _posts/index.html
exclude:
  - README.md

collections:
  projects:
    output: true
    permalink: /projects/:path.html
  posts:
    output: true
    permalink: /blog/:path.html

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  # set header offset for markdown parser as we use h1 as page title, so headers
  # in the content need to start at h2
  header_offset: 1
